/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Bootloadable_1.h"
#include "Step.h"
#include "Step_aliases.h"
#include "Dir.h"
#include "Dir_aliases.h"
#include "QuadA.h"
#include "QuadA_aliases.h"
#include "QuadB.h"
#include "QuadB_aliases.h"
#include "StepDirCounterWrap.h"
#include "QuadCounterWrap.h"
#include "QuadDec_1.h"
#include "StepDirCounter.h"
#include "Clock_1.h"
#include "PIDLoopInt.h"
#include "PIDTimer.h"
#include "MotorPWM.h"
#include "MotorControlReg.h"
#include "MotorA.h"
#include "MotorA_aliases.h"
#include "MotorB.h"
#include "MotorB_aliases.h"
#include "SerialDataInt.h"
#include "SerialDataTimer.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "LedPin.h"
#include "LedPin_aliases.h"
#include "Clock_2.h"
#include "Clock_3.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "UART_1_SCB_IRQ.h"
#include "UART_1_rx.h"
#include "UART_1_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

